# Generated by Django 5.0.1 on 2024-01-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
