# Generated by Django 5.0.1 on 2024-01-30 04:55

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slot_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot_start',
            field=models.DateTimeField(default=booking.models.TimeSlot.get_default_start_time),
        ),
    ]
