# Generated by Django 5.0.1 on 2024-02-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_timeslot_slot_end_alter_timeslot_slot_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='patient_available',
            field=models.IntegerField(default=5),
        ),
    ]
