# Generated by Django 5.0.1 on 2024-02-09 23:16

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_timeslot_patient_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_temp',
            name='date_start',
            field=models.DateTimeField(default=booking.models.Appointment_temp.get_default_start_time),
        ),
        migrations.AlterField(
            model_name='appointment_temp',
            name='date_stop',
            field=models.DateTimeField(default=booking.models.Appointment_temp.get_default_end_time),
        ),
    ]
