# Generated by Django 5.0.1 on 2024-02-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_appointment_temp_date_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention_temp',
            name='duration',
        ),
    ]
