# Generated by Django 5.0.1 on 2024-01-23 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_TMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullename', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('Service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'verbose_name': 'Doctor_TMP',
                'verbose_name_plural': 'Doctors_TMP',
            },
        ),
    ]
