# Generated by Django 5.0.1 on 2024-01-24 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_doctor_tmp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_tmp',
            old_name='Service',
            new_name='service',
        ),
    ]
