# Generated by Django 5.0.1 on 2024-01-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_service_doctor_tmp_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_tmp',
            old_name='fullename',
            new_name='fullname',
        ),
    ]
