# Generated by Django 5.0.1 on 2024-02-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='duration',
        ),
    ]
